parameters:
#    tgoudouneix_rg_score.example.class: tgoudouneix\RGScoreBundle\Example

services:
#    tgoudouneix_rg_score.example:
#        class: %tgoudouneix_rg_score.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
