<?php

namespace tgoudouneix\RGScoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JeuRepository extends EntityRepository
{
}
